import os
import requests

hero_names = [
    "abaddon", 
    "abyssal_underlord",
    "alchemist", 
    "ancient_apparition",
    "antimage",
    "arc_warden",
    "axe",
    "bane",
    "batrider",
    "beastmaster", 
    "bloodseeker", 
    "bounty_hunter",
    "brewmaster",
    "bristleback",
    "broodmother",
    "centaur",
    "chaos_knight",
    "chen",
    "clinkz",
    "crystal_maiden", 
    "dark_seer", 
    "dark_willow",
    "dawnbreaker",
    "dazzle", 
    "death_prophet", 
    "disruptor", 
    "doom_bringer",
    "dragon_knight", 
    "drow_ranger",
    "earth_spirit", 
    "earthshaker", 
    "elder_titan", 
    "ember_spirit", 
    "enchantress",
    "enigma",
    "faceless_void", 
    "furion",
    "grimstroke", 
    "gyrocopter", 
    "hoodwink",
    "huskar", 
    "invoker", 
    "jakiro",
    "juggernaut", 
    "keeper_of_the_light", 
    "kez",
    "kunkka",
    "legion_commander", 
    "leshrac",
    "lich", 
    "life_stealer",
    "lina", 
    "lion", 
    "lone_druid",
    "luna",
    "lycan",
    "magnataur",
    "marci",
    "mars",
    "medusa",
    "meepo",
    "mirana",
    "monkey_king",
    "morphling", 
    "muerta",
    "naga_siren", 
    "necrolyte",
    "nevermore", 
    "night_stalker", 
    "nyx_assassin", 
    "obsidian_destroyer",
    "ogre_magi", 
    "omniknight", 
    "oracle",
    "pangolier",
    "phantom_assassin", 
    "phantom_lancer", 
    "phoenix",
    "primal_beast",
    "puck", 
    "pudge",
    "pugna", 
    "queenofpain", 
    "rattletrap", 
    "razor", 
    "riki", 
    "ringmaster",
    "rubick", 
    "sand_king", 
    "shadow_demon", 
    "shadow_shaman", 
    "shredder",
    "silencer", 
    "skeleton_king",
    "skywrath_mage", 
    "slardar", 
    "slark",
    "snapfire",
    "sniper", 
    "spectre", 
    "spirit_breaker",
    "storm_spirit", 
    "sven",
    "techies",
    "templar_assassin",
    "terrorblade",
    "tidehunter",
    "tinker",
    "tiny",
    "treant",
    "troll_warlord",
    "tusk",
    "undying",  
    "ursa",
    "vengefulspirit",
    "venomancer",
    "viper",
    "visage",
    "void_spirit",
    "warlock",
    "weaver",   
    "windrunner",
    "winter_wyvern",
    "wisp",
    "witch_doctor",
    "zuus",
]

base_url = "https://cdn.akamai.steamstatic.com/apps/dota2/images/dota_react/heroes/"
save_dir = "src/img/heroes"

os.makedirs(save_dir, exist_ok=True)

for hero in hero_names:
    url = f"{base_url}{hero}.png"
    dest = os.path.join(save_dir, f"{hero}.png")

    print(f"Downloading {hero}...")
    response = requests.get(url)
    if response.status_code == 200:
        with open(dest, 'wb') as f:
            f.write(response.content)
    else:
        print(f"Failed to download {hero}: HTTP {response.status_code}")
